import calculus_functions_taking_values_infinite_lemma_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace calculus_functions_taking_values_infinite_lemma_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end calculus_functions_taking_values_infinite_lemma_canonical_lane_mathlib
end HautevilleHouse
